### DISCUSSION TITLE
How to include my own yaml - Files

### DISCUSSION THREAD

**Discussion by bcs-luggi** [GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200#10] [General]
Hi, it's me agin :)

As my configuartion is different form yours I have to change some values.
As far as I understand the projekt, the froeling.yaml refers to the yaml files in your
repository here on github.

How to include my own yaml's?

I've tries with:
packages: !include_dir_named froeling

but I think the syntax is wrong.

**Comment by GyroGearl00se** [comment]
if you want to have your modified files locally in your ESPHome instance you could include them like this:

```
packages:
  austragung: !include froeling/austragung.yaml
  boiler_01: !include froeling/boiler_01.yaml
  heizkoerper: !include froeling/heizkoerper.yaml
  kessel: !include froeling/kessel.yaml
  puffer_01: !include froeling/puffer_01.yaml
  zirkulationspumpe: !include froeling/zirkulationspumpe.yaml
```

Basically you can just create a subfolder in your ESPHome config directory (in this example called "froeling") and place there your personal yaml file and reference to it. No need to separate them in the categories like I've done here in this example. But I think it just gives you a better overview.

May I ask how your configuration looks like ? What components do you have ? If you're using "Fröling Connect" App, could you provide some screenshots ? I'm just curios if it would make sense to include them into this repository as well. Then everyone could just comment out maybe the yaml files where they don't have the component for it ?
