### ISSUE TITLE
Fehler in yaml Dateien?

### ISSUE THREAD

**Issue by wavoigt** [GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200#3]
Ich hab mir mal die Mühe gemacht, die Register Adressen mit der Fröhling Tabelle zu vergleichen, und bin auf folgende Unstimmigkeiten gestossen:
(Referenz: Kommunikationsprotokoll ModBus Lambdatronic 3200 V 50.04 - B 05.17 B1200419_de | Ausgabe 07.05.2019)

```
1. Kessel.yaml

---------------

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Saugzug - Ansteuerung"
    id: ${name}_Saugzug_Ansteuerung
    register_type: read
#!!! adress 12 anstatt 13
    address: 12
    unit_of_measurement: "%"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} Sekundärluft"
    id: ${name}_Sekundaerluft
    register_type: read
#!!! adress 13 anstatt 12
    address: 13
    unit_of_measurement: "%"
    value_type: U_WORD


2. heizkoerper.yaml
-------------------
number:
  # not correct yet ?
#!!! fehlt da nicht der register_type?
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Gewünschte Vorlauf-temperatur bei -10°C Außentemperatur"
    id: ${name}_HK1_Vorlauf_Temperatur_minus_10C_Aussentemperatur
    address: 1032
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 110

```
